name: bingo
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  animated_button: ^0.2.0
  shared_preferences: ^2.2.3
  http: ^1.2.0
  scroll_date_picker: ^3.8.0
  permission_handler: ^11.3.1
  simple_barcode_scanner: ^0.1.1
  animated_text_kit: ^4.2.2

  flutter_localizations:
    sdk: flutter
  extended_masked_text: ^2.3.1

  flutter_launcher_icons: ^0.14.3

dependency_overrides:

  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/bingo.ico"

flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons
    

