name: bingo
description: 'App para la gestión de bingo'
publish_to: 'none' 

version: 1.0.11

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.9
  animated_button: ^0.3.1
  shared_preferences: ^2.5.5
  http: ^1.6.0
  scroll_date_picker: ^3.8.0
  permission_handler: ^13.0.1
  animated_text_kit: ^4.2.2
  provider: ^6.1.2
  flutter_plugin_android_lifecycle: ^2.0.35
  mobile_scanner: ^7.4.0
  package_info_plus: ^10.2.1
  lottie: ^3.5.1
  msix: ^3.18.0
  flutter_bloc: ^9.1.1
  udp: ^5.0.3
  intl: ^0.20.3
  extended_masked_text: ^3.0.1

  flutter_launcher_icons: ^0.14.3

dependency_overrides:
  cli_util: ^0.5.2
  material_color_utilities: ^0.13.1
  meta: ^1.19.0
  vector_math: ^2.4.2

dev_dependencies:
  flutter_lints: ^6.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/bingo.ico"

msix_config:
  display_name: APP Bingo
  publisher_display_name: Colinktek S.A.S
  identity_name: www.colinktek.com
  msix_version: 1.0.0.0
  logo_path: assets/icons/bingo.ico
  start_menu_icon_path: assets/icons/bingo.ico
  tile_icon_path: assets/icons/bingo.ico
  vs_generated_images_folder_path: windows/runner/resources
  install_certificate: false

flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/bingo.json
    

